image: "python:3.7"

before_script:
  - python --version
  - pip install .

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 bild/*.py
    
    