image: "python:3.7"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python --version
  - pip install .

stages:
  - Analysis
  - Test

flake8:
  stage: Analysis
  script:
  - pip install flake8 --quiet
  - flake8 --max-line-length=120 bild/*.py
  
pytest:
  stage: Test
  script:
  - pip install pytest --quiet
  - pip install pytest-cov
  - pytest --cov=rates tests/
    
    