image: "python:3.7"

before_script:
  - python --version
  - pip install .

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - pip install flake8
  - flake8 --max-line-length=120 bild/*.py
  
unit_test:
  stage: Test
  script:
  - pip install pytest
  - cd tests
  - pwd
  - python -m pytest
    
    